### ISSUE TITLE
not updating ip haproxy.cfg

### ISSUE THREAD

**Issue by spijker** [Mikroways/rancher-haproxy#1]
If I do an upgrade of the docker container inside rancher, the IP is gonna change.
The option reuse IP is not always ( not ) working, see https://github.com/rancher/rancher/issues/5410
After the upgrade I need to manual restart the LB service so that it's rebuilding the config, and it's all working again for that image, or manual exec : /usr/bin/confd -interval 5 -backend rancher -prefix /2015-12-19 -node rancher-metadata

Great peace of code ;)

**Comment by chrodriguez** [comment]
@spijker I don't know how to reproduce this problem. Which container are you upgrading? One that is dynamically configured?

**Comment by spijker** [comment]
Its a semi dynamically configured, except the internal port
  ports:
- :80/tcp
  labels:
    io.rancher_haproxy.exposed_port: '80'
    io.rancher.container.pull_image: always
    io.rancher_haproxy.force_ssl.domain.tld: 'true'
    io.rancher_haproxy.server_names: domain.tld

If I do the option -> upgrade container,  the container is deployed somewhere else inside the cattle cluster, with a new IP and exposed port, but haproxy isn't updating the config.
When I do -> create new service the haproxy works correctly, or after a restart of the LB.
Tried several combinations , with or without ssl redirection, in the same or different stacks.
Always hitting a 503, service Unavailable.
Docker version 1.12.1, build 23cf638 and rancher v1.1.3, using cattle. and version 1.1.1 of 
Mikroways/rancher-haproxy

**Comment by chrodriguez** [comment]
I've just tested and it worked for me, but a co-worker reported me the same issue. I think it may be that the upgraded service is upgrading too fast (less than the confd pooling interval of 5 seconds). 
Try lowering this value specifying an environment variable called: `CONFD_INTERVAL` in the rancher-haproxy container and give it another try
Thanks for reporting, I'll be watching if it happens again

**Comment by spijker** [comment]
Great ! changed the CONF_INTERVAL to 4 , and it works.
