### ISSUE TITLE
force_ssl 

### ISSUE THREAD

**Issue by spijker** [Mikroways/rancher-haproxy#2]
If the label is defined :  io.rancher_haproxy.force_ssl.  it doens't matter if you use a true or false or whatever statement, It will always redirect with https.
Is it possible if the option is defined as false, the haproxy would ignore it ?

**Comment by kloktech-mark** [comment]
just hit this yesterday too, though it was set to false, it's still forced to ssl.

**Comment by chrodriguez** [comment]
Yes, it checks the label existence, not its value: https://github.com/Mikroways/rancher-haproxy/blob/master/confd/haproxy.cfg.tmpl#L36

```go
if exists (printf "/stacks/%s/services/%s/labels/io.rancher_haproxy.force_ssl.%s" $stack_name $service_name $name)
```

If you can upgrade your rancher infrastructure, consider using provided load balancer. Now it's as powerful as this docker image
