### ISSUE TITLE
How to use with GCP? (Google Cloud Platform)

### ISSUE THREAD

**Issue by NotoriousRebel** [Mikroways/rancher-haproxy#6]
Just discovered this repo and seems pretty great, I currently have an edge proxy for clusters with my apps with rancher v2. The script does not work with google cloud as there is no eth0 interface. Also, are there any blog posts detailing how to use this with some examples perhaps?

**Comment by chrodriguez** [comment]
This project is absolutely out of date. It was used when rancher 1.x was used. If you're using rancher2 you shall be using some ingress controller.

Hope the answer helps you!
